const graphService = require('../services/graphService');

/**
 * These definitions strictly adhere to the Model Context Protocol (MCP) tool schema.
 * They describe EXACTLY what the AI model needs to provide to trigger our Graph services.
 */
const TOOLS = [
  {
    name: "read_emails",
    description: "Fetch the latest emails from your Outlook inbox.",
    inputSchema: {
      type: "object",
      properties: {
        top: {
          type: "number",
          description: "Number of emails to fetch (default: 10)"
        }
      }
    }
  },
  {
    name: "search_emails",
    description: "Search for specific emails based on a keyword.",
    inputSchema: {
      type: "object",
      properties: {
        keyword: {
          type: "string",
          description: "The keyword to search for"
        }
      },
      required: ["keyword"]
    }
  },
  {
    name: "send_email",
    description: "Send an email to a specific recipient.",
    inputSchema: {
      type: "object",
      properties: {
        to: { type: "string", description: "Recipient email address" },
        subject: { type: "string", description: "Subject of the email" },
        body: { type: "string", description: "Body/content of the email" }
      },
      required: ["to", "subject", "body"]
    }
  },
  {
    name: "get_calendar_events",
    description: "Fetch upcoming calendar events.",
    inputSchema: {
      type: "object",
      properties: {
        daysLookAhead: {
          type: "number",
          description: "How many days ahead to look for events (default: 7)"
        }
      }
    }
  },
  {
    name: "create_calendar_event",
    description: "Create a new calendar event.",
    inputSchema: {
      type: "object",
      properties: {
        title: { type: "string", description: "Title of the event" },
        startTime: { type: "string", description: "Start time in UTC ISO format (e.g. 2026-04-05T10:00:00Z)" },
        endTime: { type: "string", description: "End time in UTC ISO format (e.g. 2026-04-05T11:00:00Z)" }
      },
      required: ["title", "startTime", "endTime"]
    }
  }
];

/**
 * Maps the tool call generated by the AI to our internal Graph service functions.
 * Includes explicit validation mechanisms to catch hallucinated arguments from the LLM.
 */
async function handleToolCall(name, args) {
    switch (name) {
        case "read_emails":
            return await graphService.fetchEmails(args.top || 10);
            
        case "search_emails":
            // Input Validation Fallback
            if (!args.keyword) throw new Error("Missing required argument: keyword");
            return await graphService.searchEmails(args.keyword);
            
        case "send_email":
            if (!args.to || !args.subject || !args.body) {
                throw new Error("Missing required arguments for sending email (to, subject, body).");
            }
            return await graphService.sendEmail(args.to, args.subject, args.body);
            
        case "get_calendar_events":
            return await graphService.getCalendarEvents(args.daysLookAhead || 7);
            
        case "create_calendar_event":
            if (!args.title || !args.startTime || !args.endTime) {
                throw new Error("Missing required arguments for creating event (title, startTime, endTime).");
            }
            return await graphService.createEvent(args.title, args.startTime, args.endTime);
            
        default:
            throw new Error(`Unknown tool requested: ${name}`);
    }
}

module.exports = {
    TOOLS,
    handleToolCall
};
